version: '3'

services:

  moip-challenge-api:
    container_name: moip-challenge-api
    build:
      context: .
    volumes:
      - ./build/libs/:/moip
    environment:
      SPRING_PROFILES_ACTIVE: development
      MYSQL_URL: jdbc:mysql://moip-challenge-mysql/moip_challenge
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - moip-challenge-mysql

  moip-challenge-mysql:
    container_name: moip-challenge-mysql
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moip_challenge
