version: '3'

services:

  api:
    build:
      context: .
    volumes:
      - ./build/libs/:/moip
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_URL: jdbc:mysql://mysql:3306/moip?useSSL=false
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moip
