version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: ./gradlew build
      - run:
        name: Code coverage
        command: |
          ./gradlew jacocoTestReport
          ./gradlew jacocoTestCoverageVerification
          bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build